language: node_js
node_js:
  - 14.15.4
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  npm: true
  directories:
    - ~/.cache
install:
  - yarn
script:
  - $(yarn bin)/cypress run --parallel
